#!/usr/bin/env ruby

require 'slim'

parser = Slim::Parser.new(attr_list_delims: { '(' => ')', '[' => ']' })

def render(io, expression, depth=0, options={})
  case expression[0]
  when :multi
    expression[1..-1].each { |expr| render io, expr, depth, options }

  when :newline
    io.print "\n" unless options[:newline] == false

  when :static
    io.print expression[1]

  when :escape
    render buf = StringIO.new, expression[2], depth, options
    io.print buf.string.inspect

  when :html
    case expression[1]
    when :doctype
      io.print "doctype #{expression[2]}"
    when :tag
      expression[2] = '' if expression[2] == '#' || expression[2] == '.'
      expression[3] = expression[3].reject do |expr|
        if expr.instance_of?(Array) && expr[3][0] == :static
          case expr[2]
          when 'id'
            expression[2] += '#' + expr[3][1]
          when 'class'
            expression[2] += '.' + expr[3][1]
          end
        end
      end

      io.print '  '*depth, expression[2]
      # handle `:`s
      if expression[4][0] == :multi && expression[4][1] != [:newline]
        expression[4].insert 1, [:newline]
      end
      expression[3..-1].each { |expr| render io, expr, depth+1, options }
    when :attrs
      if expression[2]
        io.print '('
        expression[2..-1].each do |expr|
          io.print ' '
          render io, expr, depth, options
        end
        io.print ' )'
      end
    when :attr
      io.print expression[2], '='
      render io, expression[3], depth, options
    else
      warn 'unhandled', expression.inspect
    end

  when :slim
    case expression[1]
    when :interpolate
      io.print expression[2]

    when :attrvalue
      io.print expression[3]

    when :control
      warn 'Cannot hang with control statements', expression.inspect

    when :text
      render buf = StringIO.new, expression[3], depth, newline: false
      case expression[2]
      when :inline
        io.print ' '
        io.print buf.string.gsub("\n", "\n" + '  ' * depth + '| ')
      when :verbatim
        io.print buf.string.gsub(/^/, '  ' * depth + '| ')
      else
        warn expression.inspect
      end

    when :embedded
      case expression[2]
      when 'javascript'
        io.print '  ' * depth, 'script.', "\n"
        render buf = StringIO.new, expression[3], depth+1, newline: false
        io.print buf.string.gsub(/^/, '  ' * (depth+1))
      else
        warn 'unhandled', expression
      end

    else
      warn expression.inspect

    end

  else
    warn expression.inspect

  end
end

File.open ARGV[0] do |file|
  expression = parser.call(file.read)
  p expression
  render STDOUT, expression
end
